# Generated by Django 5.1.1 on 2024-10-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_video', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='call_link',
            field=models.URLField(blank=True, help_text='Link for the call'),
        ),
    ]
