# Generated by Django 5.1.1 on 2024-10-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='group',
            name='mentor_count',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
