# Generated by Django 5.1.1 on 2024-10-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_group_admin_group_admins_group_mentee_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='group_logos/'),
        ),
    ]
