# Generated by Django 5.1.1 on 2024-10-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_group_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sender_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
