# Generated by Django 5.1.1 on 2024-10-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_content_groupmessage_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='sender_profile_picture',
            new_name='profile_picture',
        ),
    ]
