# Generated by Django 5.1.1 on 2024-11-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
