# Generated by Django 5.1.1 on 2025-08-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_group_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
