# Generated by Django 5.1.1 on 2025-08-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_groupmessage_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
