# Generated by Django 5.1.1 on 2025-06-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_accountdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='bank_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
