# Generated by Django 5.1.1 on 2025-08-29 14:45

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_sessionpayment_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='sessionpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionpayment',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUNDED', 'Partially Refunded')], default='INITIATED', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='phonepe_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUND_COMPLETED', 'Refund Completed'), ('REFUND_FAILED', 'Refund Failed')], default='INITIATED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sessionpayment',
            index=models.Index(fields=['session_id'], name='session_pay_session_82af09_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionpayment',
            index=models.Index(fields=['status'], name='session_pay_status_c27fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionpayment',
            index=models.Index(fields=['created_at'], name='session_pay_created_c4c043_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction_id'], name='transaction_transac_567f79_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['phonepe_transaction_id'], name='transaction_phonepe_dd5c29_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['status'], name='transaction_status_e0b67e_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['created_at'], name='transaction_created_644523_idx'),
        ),
        migrations.AlterModelTable(
            name='sessionpayment',
            table='session_payments',
        ),
        migrations.AlterModelTable(
            name='transactionlog',
            table='transaction_logs',
        ),
    ]
