# Generated by Django 5.1.1 on 2025-06-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_platformearnings_sessionpayment_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformearnings',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='platformearnings',
            name='withdrawable_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
