# Generated by Django 5.1.1 on 2025-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_mentorearning_delete_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorearning',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mentorearning',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
