# Generated by Django 5.1.1 on 2025-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, default='static_files/group_logos/mentifflogo.png', null=True, upload_to='static_files/group_logos/'),
        ),
    ]
