# Generated by Django 5.1.1 on 2024-10-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_year_of_study_mentor_year_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='session_fee',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
    ]
