# Generated by Django 5.1.1 on 2024-10-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_mentor_session_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='available_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='available_hours',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
