# Generated by Django 5.1.1 on 2024-10-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='mentor',
            name='session_time',
            field=models.CharField(default='30 Mins', max_length=50),
        ),
    ]
