# Generated by Django 5.1.1 on 2024-10-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_mentor_currency_mentor_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
