# Generated by Django 5.1.1 on 2024-10-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_mentor_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='available_hours',
        ),
        migrations.AddField(
            model_name='mentor',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
