# Generated by Django 5.1.1 on 2024-10-22 09:43

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_mentor_available_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='availability',
            field=models.JSONField(blank=True, default=users.models.Mentor.default_availability),
        ),
    ]
