# Generated by Django 5.1.1 on 2024-11-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_mentee_college_mentor_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_dp.jpg', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_dp.jpg', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_dp.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
