# Generated by Django 5.1.1 on 2025-08-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_mentee_google_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='calls_booked',
            field=models.IntegerField(default=0),
        ),
    ]
