# Generated by Django 5.1.1 on 2025-08-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_mentoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoravailability',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
        migrations.AlterField(
            model_name='mentoravailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentoravailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
