# Generated by Django 5.1.1 on 2025-08-16 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_mentoravailability_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='session_fee',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='session_time',
        ),
        migrations.CreateModel(
            name='SessionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_options', to='users.mentor')),
            ],
            options={
                'unique_together': {('mentor', 'duration_minutes')},
            },
        ),
    ]
