# Generated by Django 5.1.1 on 2025-08-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_mentor_currency_remove_mentor_session_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='session_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
