# Generated by Django 5.1.1 on 2025-08-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_feedback_session_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('mentor', 'mentee')},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='session_date',
        ),
    ]
