# Generated by Django 5.1.1 on 2025-08-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_feedback_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
    ]
