# Generated by Django 5.1.1 on 2025-08-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_feedback_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
    ]
