# Generated by Django 5.1.1 on 2025-08-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_mentor_city_mentor_state_mentor_university_domain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='city',
            new_name='university_city',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='state',
            new_name='university_state',
        ),
    ]
