# Generated by Django 5.1.1 on 2025-08-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_rename_city_mentor_university_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
