# Generated by Django 5.1.1 on 2024-11-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_mentor_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
