# Generated by Django 5.1.1 on 2024-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('notInitiated', 'NotInitiated'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='notInitiated', max_length=15),
        ),
    ]
