# Generated by Django 5.1.1 on 2024-10-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('issue raised', 'Issue Raised'), ('issue resolved', 'Issue Resolved')], default='pending', max_length=20),
        ),
    ]
