# Generated by Django 5.1.1 on 2024-10-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_video', '0003_booking_call_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='call_link',
            field=models.URLField(blank=True, help_text='Link for the call', null=True),
        ),
    ]
